import type { AIProvider, ModelInfo, ProviderConfig, TaskType } from './types';

export const PROVIDERS: Record<AIProvider, ProviderConfig> = {
  claude: {
    id: 'claude',
    name: 'Claude',
    color: '#a855f7',
    glowClass: 'glow-purple',
    borderClass: 'neon-border-purple',
    textClass: 'text-neon-claude',
    bgClass: 'bg-neon-claude',
    icon: '◆',
    website: 'https://console.anthropic.com',
  },
  openai: {
    id: 'openai',
    name: 'OpenAI',
    color: '#10b981',
    glowClass: 'glow-green',
    borderClass: 'neon-border-green',
    textClass: 'text-neon-openai',
    bgClass: 'bg-neon-openai',
    icon: '⬡',
    website: 'https://platform.openai.com',
  },
  gemini: {
    id: 'gemini',
    name: 'Gemini',
    color: '#3b82f6',
    glowClass: 'glow-blue',
    borderClass: 'neon-border-blue',
    textClass: 'text-neon-gemini',
    bgClass: 'bg-neon-gemini',
    icon: '✦',
    website: 'https://aistudio.google.com',
  },
  groq: {
    id: 'groq',
    name: 'Groq',
    color: '#f59e0b',
    glowClass: 'glow-amber',
    borderClass: 'neon-border-amber',
    textClass: 'text-neon-groq',
    bgClass: 'bg-neon-groq',
    icon: '⚡',
    website: 'https://console.groq.com',
  },
};

export const MODELS: ModelInfo[] = [
  // Claude / Anthropic
  {
    id: 'claude-opus-4-6',
    provider: 'claude',
    name: 'Claude Opus 4.6',
    inputCostPer1M: 15,
    outputCostPer1M: 75,
    contextWindow: 200000,
    description: 'Most capable Claude model for complex reasoning',
    strengths: ['coding', 'analysis', 'creative'],
    speed: 'slow',
    releasedAt: '2025-08',
  },
  {
    id: 'claude-sonnet-4-6',
    provider: 'claude',
    name: 'Claude Sonnet 4.6',
    inputCostPer1M: 3,
    outputCostPer1M: 15,
    contextWindow: 200000,
    description: 'Best balance of intelligence and speed',
    strengths: ['coding', 'analysis', 'chat'],
    speed: 'medium',
    releasedAt: '2025-07',
  },
  {
    id: 'claude-haiku-4-5',
    provider: 'claude',
    name: 'Claude Haiku 4.5',
    inputCostPer1M: 0.8,
    outputCostPer1M: 4,
    contextWindow: 200000,
    description: 'Fastest and most compact Claude model',
    strengths: ['chat', 'search'],
    speed: 'fast',
    releasedAt: '2025-06',
  },
  // OpenAI
  {
    id: 'gpt-4o',
    provider: 'openai',
    name: 'GPT-4o',
    inputCostPer1M: 2.5,
    outputCostPer1M: 10,
    contextWindow: 128000,
    description: 'Flagship multimodal model',
    strengths: ['coding', 'analysis', 'creative', 'chat'],
    speed: 'medium',
    releasedAt: '2024-05',
  },
  {
    id: 'gpt-4o-mini',
    provider: 'openai',
    name: 'GPT-4o Mini',
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    contextWindow: 128000,
    description: 'Affordable and intelligent small model',
    strengths: ['chat', 'search'],
    speed: 'fast',
    releasedAt: '2024-07',
  },
  {
    id: 'o3',
    provider: 'openai',
    name: 'o3',
    inputCostPer1M: 10,
    outputCostPer1M: 40,
    contextWindow: 200000,
    description: 'Advanced reasoning model',
    strengths: ['coding', 'analysis'],
    speed: 'slow',
    releasedAt: '2025-04',
  },
  // Gemini
  {
    id: 'gemini-2.0-flash',
    provider: 'gemini',
    name: 'Gemini 2.0 Flash',
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.4,
    contextWindow: 1048576,
    description: 'Blazing fast with massive context',
    strengths: ['search', 'chat', 'analysis'],
    speed: 'fast',
    releasedAt: '2025-02',
  },
  {
    id: 'gemini-2.5-pro',
    provider: 'gemini',
    name: 'Gemini 2.5 Pro',
    inputCostPer1M: 1.25,
    outputCostPer1M: 10,
    contextWindow: 2000000,
    description: 'Most intelligent Gemini model with 2M context',
    strengths: ['coding', 'analysis', 'creative'],
    speed: 'medium',
    releasedAt: '2025-03',
  },
  // Groq
  {
    id: 'llama-3.3-70b-versatile',
    provider: 'groq',
    name: 'Llama 3.3 70B',
    inputCostPer1M: 0.59,
    outputCostPer1M: 0.79,
    contextWindow: 128000,
    description: 'Fastest LLM inference via Groq',
    strengths: ['chat', 'coding', 'search'],
    speed: 'fast',
    releasedAt: '2024-12',
  },
  {
    id: 'mixtral-8x7b-32768',
    provider: 'groq',
    name: 'Mixtral 8x7B',
    inputCostPer1M: 0.24,
    outputCostPer1M: 0.24,
    contextWindow: 32768,
    description: 'Cost-efficient mixture of experts',
    strengths: ['chat', 'creative'],
    speed: 'fast',
    releasedAt: '2024-01',
  },
];

// Task-specific quality scores (expert-rated 0-100)
export const TASK_QUALITY_SCORES: Record<string, Record<TaskType, number>> = {
  'claude-opus-4-6':       { coding: 97, creative: 95, search: 85, analysis: 98, chat: 92 },
  'claude-sonnet-4-6':     { coding: 92, creative: 90, search: 84, analysis: 93, chat: 90 },
  'claude-haiku-4-5':      { coding: 75, creative: 72, search: 78, analysis: 72, chat: 80 },
  'gpt-4o':                { coding: 93, creative: 92, search: 88, analysis: 94, chat: 93 },
  'gpt-4o-mini':           { coding: 78, creative: 75, search: 82, analysis: 76, chat: 82 },
  'o3':                    { coding: 98, creative: 80, search: 82, analysis: 99, chat: 78 },
  'gemini-2.0-flash':      { coding: 80, creative: 78, search: 92, analysis: 82, chat: 85 },
  'gemini-2.5-pro':        { coding: 91, creative: 88, search: 93, analysis: 95, chat: 88 },
  'llama-3.3-70b-versatile': { coding: 85, creative: 80, search: 83, analysis: 82, chat: 86 },
  'mixtral-8x7b-32768':    { coding: 74, creative: 72, search: 76, analysis: 72, chat: 78 },
};

// Speed scores (0-100, higher = faster)
export const SPEED_SCORES: Record<string, number> = {
  'claude-opus-4-6': 40,
  'claude-sonnet-4-6': 70,
  'claude-haiku-4-5': 90,
  'gpt-4o': 65,
  'gpt-4o-mini': 92,
  'o3': 30,
  'gemini-2.0-flash': 95,
  'gemini-2.5-pro': 60,
  'llama-3.3-70b-versatile': 95,
  'mixtral-8x7b-32768': 97,
};

export const PROVIDER_LIST: AIProvider[] = ['claude', 'openai', 'gemini', 'groq'];
