import type { AIProvider, ModelInfo, ProviderConfig, TaskType } from './types';

export const PROVIDERS: Record<AIProvider, ProviderConfig> = {
  claude: {
    id: 'claude',
    name: 'Claude',
    color: '#a855f7',
    icon: '◆',
    website: 'https://console.anthropic.com',
    accent: 'purple',
    keyHint: 'Starts with sk-ant-api03-',
    keyPrefix: 'sk-ant-',
  },
  openai: {
    id: 'openai',
    name: 'OpenAI',
    color: '#10b981',
    icon: '⬡',
    website: 'https://platform.openai.com',
    accent: 'green',
    keyHint: 'Starts with sk-proj- or sk-',
    keyPrefix: 'sk-',
  },
  gemini: {
    id: 'gemini',
    name: 'Gemini',
    color: '#3b82f6',
    icon: '✦',
    website: 'https://aistudio.google.com',
    accent: 'blue',
    keyHint: 'Starts with AIzaSy',
    keyPrefix: 'AIza',
  },
  groq: {
    id: 'groq',
    name: 'Groq',
    color: '#f59e0b',
    icon: '⚡',
    website: 'https://console.groq.com',
    accent: 'amber',
    keyHint: 'Starts with gsk_',
    keyPrefix: 'gsk_',
  },
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    color: '#8b5cf6',
    icon: '⇄',
    website: 'https://openrouter.ai/keys',
    accent: 'purple',
    keyHint: 'Starts with sk-or-',
    keyPrefix: 'sk-or-',
  },
  xai: {
    id: 'xai',
    name: 'xAI / Grok',
    color: '#94a3b8',
    icon: '✕',
    website: 'https://console.x.ai',
    accent: 'green',
    keyHint: 'Starts with xai-',
    keyPrefix: 'xai-',
  },
  mistral: {
    id: 'mistral',
    name: 'Mistral',
    color: '#f97316',
    icon: '〜',
    website: 'https://console.mistral.ai/api-keys',
    accent: 'amber',
    keyHint: 'From console.mistral.ai',
  },
  cohere: {
    id: 'cohere',
    name: 'Cohere',
    color: '#14b8a6',
    icon: '◎',
    website: 'https://dashboard.cohere.com/api-keys',
    accent: 'blue',
    keyHint: 'Command R series',
  },
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity',
    color: '#06b6d4',
    icon: '∞',
    website: 'https://www.perplexity.ai/settings/api',
    accent: 'blue',
    keyHint: 'Starts with pplx-',
    keyPrefix: 'pplx-',
  },
  together: {
    id: 'together',
    name: 'Together AI',
    color: '#22c55e',
    icon: '⊕',
    website: 'https://api.together.xyz/settings/api-keys',
    accent: 'green',
    keyHint: 'Open-source models at scale',
  },
  fireworks: {
    id: 'fireworks',
    name: 'Fireworks AI',
    color: '#fb923c',
    icon: '✺',
    website: 'https://fireworks.ai/account/api-keys',
    accent: 'amber',
    keyHint: 'Fast open-source inference',
  },
  huggingface: {
    id: 'huggingface',
    name: 'HuggingFace',
    color: '#fbbf24',
    icon: '🤗',
    website: 'https://huggingface.co/settings/tokens',
    accent: 'amber',
    keyHint: 'Starts with hf_',
    keyPrefix: 'hf_',
  },
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    color: '#6366f1',
    icon: '◉',
    website: 'https://platform.deepseek.com/api_keys',
    accent: 'blue',
    keyHint: 'Starts with sk-',
    keyPrefix: 'sk-',
  },
  ollama: {
    id: 'ollama',
    name: 'Ollama',
    color: '#84cc16',
    icon: '⬟',
    website: 'https://ollama.ai',
    accent: 'green',
    keyHint: 'Local — no API key needed (type any value)',
    isLocal: true,
  },
  azure: {
    id: 'azure',
    name: 'Azure OpenAI',
    color: '#0ea5e9',
    icon: '☁',
    website: 'https://portal.azure.com',
    accent: 'blue',
    keyHint: 'Azure resource key',
    requiresBaseUrl: true,
  },
  bedrock: {
    id: 'bedrock',
    name: 'AWS Bedrock',
    color: '#f59e0b',
    icon: '◈',
    website: 'https://console.aws.amazon.com/bedrock',
    accent: 'amber',
    keyHint: 'AWS Access Key ID (IAM-based)',
  },
  replicate: {
    id: 'replicate',
    name: 'Replicate',
    color: '#ec4899',
    icon: '⟳',
    website: 'https://replicate.com/account/api-tokens',
    accent: 'purple',
    keyHint: 'Starts with r8_',
    keyPrefix: 'r8_',
  },
};

export const MODELS: ModelInfo[] = [
  // ── Claude / Anthropic ──────────────────────────────────
  {
    id: 'claude-opus-4-6',
    provider: 'claude',
    name: 'Claude Opus 4.6',
    inputCostPer1M: 15,
    outputCostPer1M: 75,
    contextWindow: 200000,
    description: 'Most capable Claude model for complex reasoning',
    strengths: ['coding', 'analysis', 'creative'],
    speed: 'slow',
    releasedAt: '2025-08',
  },
  {
    id: 'claude-sonnet-4-6',
    provider: 'claude',
    name: 'Claude Sonnet 4.6',
    inputCostPer1M: 3,
    outputCostPer1M: 15,
    contextWindow: 200000,
    description: 'Best balance of intelligence and speed',
    strengths: ['coding', 'analysis', 'chat'],
    speed: 'medium',
    releasedAt: '2025-07',
  },
  {
    id: 'claude-haiku-4-5',
    provider: 'claude',
    name: 'Claude Haiku 4.5',
    inputCostPer1M: 0.8,
    outputCostPer1M: 4,
    contextWindow: 200000,
    description: 'Fastest and most compact Claude model',
    strengths: ['chat', 'search'],
    speed: 'fast',
    releasedAt: '2025-06',
  },
  // ── OpenAI ─────────────────────────────────────────────
  {
    id: 'gpt-4o',
    provider: 'openai',
    name: 'GPT-4o',
    inputCostPer1M: 2.5,
    outputCostPer1M: 10,
    contextWindow: 128000,
    description: 'Flagship multimodal model',
    strengths: ['coding', 'analysis', 'creative', 'chat'],
    speed: 'medium',
    releasedAt: '2024-05',
  },
  {
    id: 'gpt-4o-mini',
    provider: 'openai',
    name: 'GPT-4o Mini',
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    contextWindow: 128000,
    description: 'Affordable and intelligent small model',
    strengths: ['chat', 'search'],
    speed: 'fast',
    releasedAt: '2024-07',
  },
  {
    id: 'o3',
    provider: 'openai',
    name: 'o3',
    inputCostPer1M: 10,
    outputCostPer1M: 40,
    contextWindow: 200000,
    description: 'Advanced reasoning model',
    strengths: ['coding', 'analysis'],
    speed: 'slow',
    releasedAt: '2025-04',
  },
  {
    id: 'o4-mini',
    provider: 'openai',
    name: 'o4-mini',
    inputCostPer1M: 1.1,
    outputCostPer1M: 4.4,
    contextWindow: 200000,
    description: 'Fast, affordable reasoning model',
    strengths: ['coding', 'analysis', 'chat'],
    speed: 'medium',
    releasedAt: '2025-04',
  },
  // ── Gemini ─────────────────────────────────────────────
  {
    id: 'gemini-2.0-flash',
    provider: 'gemini',
    name: 'Gemini 2.0 Flash',
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.4,
    contextWindow: 1048576,
    description: 'Blazing fast with massive context',
    strengths: ['search', 'chat', 'analysis'],
    speed: 'fast',
    releasedAt: '2025-02',
  },
  {
    id: 'gemini-2.5-pro',
    provider: 'gemini',
    name: 'Gemini 2.5 Pro',
    inputCostPer1M: 1.25,
    outputCostPer1M: 10,
    contextWindow: 2000000,
    description: 'Most intelligent Gemini model with 2M context',
    strengths: ['coding', 'analysis', 'creative'],
    speed: 'medium',
    releasedAt: '2025-03',
  },
  // ── Groq ───────────────────────────────────────────────
  {
    id: 'llama-3.3-70b-versatile',
    provider: 'groq',
    name: 'Llama 3.3 70B',
    inputCostPer1M: 0.59,
    outputCostPer1M: 0.79,
    contextWindow: 128000,
    description: 'Fastest LLM inference via Groq',
    strengths: ['chat', 'coding', 'search'],
    speed: 'fast',
    releasedAt: '2024-12',
  },
  {
    id: 'mixtral-8x7b-32768',
    provider: 'groq',
    name: 'Mixtral 8x7B',
    inputCostPer1M: 0.24,
    outputCostPer1M: 0.24,
    contextWindow: 32768,
    description: 'Cost-efficient mixture of experts',
    strengths: ['chat', 'creative'],
    speed: 'fast',
    releasedAt: '2024-01',
  },
  // ── OpenRouter ─────────────────────────────────────────
  {
    id: 'openrouter/auto',
    provider: 'openrouter',
    name: 'Auto (cheapest)',
    inputCostPer1M: 0.5,
    outputCostPer1M: 1.5,
    contextWindow: 128000,
    description: 'Automatically picks the cheapest available model',
    strengths: ['chat', 'search'],
    speed: 'fast',
  },
  {
    id: 'openrouter/claude-3.5-sonnet',
    provider: 'openrouter',
    name: 'Claude 3.5 Sonnet (OR)',
    inputCostPer1M: 3.3,
    outputCostPer1M: 16.5,
    contextWindow: 200000,
    description: 'Claude via OpenRouter with unified billing',
    strengths: ['coding', 'analysis', 'creative'],
    speed: 'medium',
  },
  {
    id: 'openrouter/deepseek-r1',
    provider: 'openrouter',
    name: 'DeepSeek R1 (OR)',
    inputCostPer1M: 0.55,
    outputCostPer1M: 2.19,
    contextWindow: 163840,
    description: 'Powerful reasoning model via OpenRouter',
    strengths: ['coding', 'analysis'],
    speed: 'slow',
  },
  // ── xAI / Grok ─────────────────────────────────────────
  {
    id: 'grok-3',
    provider: 'xai',
    name: 'Grok 3',
    inputCostPer1M: 3,
    outputCostPer1M: 15,
    contextWindow: 131072,
    description: "xAI's most capable model",
    strengths: ['coding', 'analysis', 'chat'],
    speed: 'medium',
    releasedAt: '2025-02',
  },
  {
    id: 'grok-3-mini',
    provider: 'xai',
    name: 'Grok 3 Mini',
    inputCostPer1M: 0.3,
    outputCostPer1M: 0.5,
    contextWindow: 131072,
    description: 'Fast and affordable Grok model',
    strengths: ['chat', 'search', 'coding'],
    speed: 'fast',
    releasedAt: '2025-02',
  },
  // ── Mistral ────────────────────────────────────────────
  {
    id: 'mistral-large-2411',
    provider: 'mistral',
    name: 'Mistral Large',
    inputCostPer1M: 2,
    outputCostPer1M: 6,
    contextWindow: 128000,
    description: "Mistral's flagship large model",
    strengths: ['coding', 'analysis', 'creative'],
    speed: 'medium',
    releasedAt: '2024-11',
  },
  {
    id: 'mistral-small-2409',
    provider: 'mistral',
    name: 'Mistral Small',
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.6,
    contextWindow: 32000,
    description: 'Cost-effective for everyday tasks',
    strengths: ['chat', 'search'],
    speed: 'fast',
    releasedAt: '2024-09',
  },
  {
    id: 'codestral-2501',
    provider: 'mistral',
    name: 'Codestral',
    inputCostPer1M: 0.3,
    outputCostPer1M: 0.9,
    contextWindow: 256000,
    description: 'Purpose-built for code generation',
    strengths: ['coding'],
    speed: 'fast',
    releasedAt: '2025-01',
  },
  // ── Cohere ─────────────────────────────────────────────
  {
    id: 'command-r-plus-08-2024',
    provider: 'cohere',
    name: 'Command R+',
    inputCostPer1M: 2.5,
    outputCostPer1M: 10,
    contextWindow: 128000,
    description: 'Cohere flagship with RAG optimization',
    strengths: ['analysis', 'search', 'coding'],
    speed: 'medium',
    releasedAt: '2024-08',
  },
  {
    id: 'command-r-08-2024',
    provider: 'cohere',
    name: 'Command R',
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    contextWindow: 128000,
    description: 'Efficient model for RAG and chat',
    strengths: ['chat', 'search'],
    speed: 'fast',
    releasedAt: '2024-08',
  },
  // ── Perplexity ─────────────────────────────────────────
  {
    id: 'sonar-pro',
    provider: 'perplexity',
    name: 'Sonar Pro',
    inputCostPer1M: 3,
    outputCostPer1M: 15,
    contextWindow: 200000,
    description: 'Advanced search-augmented reasoning',
    strengths: ['search', 'analysis'],
    speed: 'medium',
    releasedAt: '2025-01',
  },
  {
    id: 'sonar',
    provider: 'perplexity',
    name: 'Sonar',
    inputCostPer1M: 1,
    outputCostPer1M: 1,
    contextWindow: 128000,
    description: 'Fast web-connected search model',
    strengths: ['search', 'chat'],
    speed: 'fast',
    releasedAt: '2025-01',
  },
  // ── Together AI ────────────────────────────────────────
  {
    id: 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo',
    provider: 'together',
    name: 'Llama 3.1 405B Turbo',
    inputCostPer1M: 3.5,
    outputCostPer1M: 3.5,
    contextWindow: 130815,
    description: "Meta's largest open-source model",
    strengths: ['coding', 'analysis', 'creative'],
    speed: 'slow',
    releasedAt: '2024-07',
  },
  {
    id: 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo',
    provider: 'together',
    name: 'Llama 3.1 70B Turbo',
    inputCostPer1M: 0.88,
    outputCostPer1M: 0.88,
    contextWindow: 131072,
    description: 'Strong 70B model with fast inference',
    strengths: ['chat', 'coding', 'search'],
    speed: 'fast',
    releasedAt: '2024-07',
  },
  // ── Fireworks AI ───────────────────────────────────────
  {
    id: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
    provider: 'fireworks',
    name: 'Llama 3.1 70B (FW)',
    inputCostPer1M: 0.9,
    outputCostPer1M: 0.9,
    contextWindow: 131072,
    description: 'Ultra-fast Llama inference via Fireworks',
    strengths: ['chat', 'coding'],
    speed: 'fast',
    releasedAt: '2024-07',
  },
  {
    id: 'accounts/fireworks/models/deepseek-r1',
    provider: 'fireworks',
    name: 'DeepSeek R1 (FW)',
    inputCostPer1M: 3,
    outputCostPer1M: 8,
    contextWindow: 163840,
    description: 'DeepSeek reasoning via Fireworks',
    strengths: ['coding', 'analysis'],
    speed: 'slow',
    releasedAt: '2025-01',
  },
  // ── HuggingFace ────────────────────────────────────────
  {
    id: 'meta-llama/Meta-Llama-3.1-8B-Instruct',
    provider: 'huggingface',
    name: 'Llama 3.1 8B (HF)',
    inputCostPer1M: 0.0,
    outputCostPer1M: 0.0,
    contextWindow: 128000,
    description: 'Free tier via HuggingFace Inference API',
    strengths: ['chat', 'search'],
    speed: 'medium',
    releasedAt: '2024-07',
  },
  {
    id: 'mistralai/Mistral-7B-Instruct-v0.3',
    provider: 'huggingface',
    name: 'Mistral 7B (HF)',
    inputCostPer1M: 0.0,
    outputCostPer1M: 0.0,
    contextWindow: 32000,
    description: 'Fast open model via HuggingFace',
    strengths: ['chat', 'creative'],
    speed: 'fast',
    releasedAt: '2024-05',
  },
  // ── DeepSeek ───────────────────────────────────────────
  {
    id: 'deepseek-chat',
    provider: 'deepseek',
    name: 'DeepSeek V3',
    inputCostPer1M: 0.27,
    outputCostPer1M: 1.1,
    contextWindow: 64000,
    description: 'Exceptionally cost-effective general model',
    strengths: ['coding', 'chat', 'analysis'],
    speed: 'medium',
    releasedAt: '2024-12',
  },
  {
    id: 'deepseek-reasoner',
    provider: 'deepseek',
    name: 'DeepSeek R1',
    inputCostPer1M: 0.55,
    outputCostPer1M: 2.19,
    contextWindow: 64000,
    description: 'Chain-of-thought reasoning powerhouse',
    strengths: ['coding', 'analysis'],
    speed: 'slow',
    releasedAt: '2025-01',
  },
  // ── Ollama (local) ─────────────────────────────────────
  {
    id: 'ollama/llama3.2',
    provider: 'ollama',
    name: 'Llama 3.2 (local)',
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    contextWindow: 128000,
    description: 'Run locally for free — no data leaves your machine',
    strengths: ['chat', 'coding'],
    speed: 'medium',
    releasedAt: '2024-09',
  },
  {
    id: 'ollama/qwen2.5-coder',
    provider: 'ollama',
    name: 'Qwen 2.5 Coder (local)',
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    contextWindow: 128000,
    description: 'Top local coding model',
    strengths: ['coding'],
    speed: 'medium',
    releasedAt: '2024-11',
  },
  // ── Azure OpenAI ───────────────────────────────────────
  {
    id: 'azure/gpt-4o',
    provider: 'azure',
    name: 'GPT-4o (Azure)',
    inputCostPer1M: 2.75,
    outputCostPer1M: 11,
    contextWindow: 128000,
    description: 'GPT-4o via Azure with enterprise SLA',
    strengths: ['coding', 'analysis', 'creative', 'chat'],
    speed: 'medium',
    releasedAt: '2024-05',
  },
  // ── AWS Bedrock ────────────────────────────────────────
  {
    id: 'bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0',
    provider: 'bedrock',
    name: 'Claude 3.5 Sonnet (Bedrock)',
    inputCostPer1M: 3,
    outputCostPer1M: 15,
    contextWindow: 200000,
    description: 'Claude via AWS Bedrock with VPC support',
    strengths: ['coding', 'analysis', 'creative'],
    speed: 'medium',
    releasedAt: '2024-10',
  },
  {
    id: 'bedrock/meta.llama3-1-70b-instruct-v1:0',
    provider: 'bedrock',
    name: 'Llama 3.1 70B (Bedrock)',
    inputCostPer1M: 0.99,
    outputCostPer1M: 0.99,
    contextWindow: 128000,
    description: 'Llama via AWS with enterprise compliance',
    strengths: ['chat', 'coding'],
    speed: 'fast',
    releasedAt: '2024-07',
  },
  // ── Replicate ──────────────────────────────────────────
  {
    id: 'meta/meta-llama-3.1-405b-instruct',
    provider: 'replicate',
    name: 'Llama 3.1 405B (Replicate)',
    inputCostPer1M: 9.5,
    outputCostPer1M: 9.5,
    contextWindow: 128000,
    description: 'Run any open model via Replicate API',
    strengths: ['coding', 'creative', 'analysis'],
    speed: 'medium',
    releasedAt: '2024-07',
  },
];

// Default core providers shown on initial load
export const CORE_PROVIDERS: AIProvider[] = ['claude', 'openai', 'gemini', 'groq'];

// Full list of all providers
export const PROVIDER_LIST: AIProvider[] = Object.keys(PROVIDERS) as AIProvider[];

// Task-specific quality scores (expert-rated 0-100)
export const TASK_QUALITY_SCORES: Record<string, Record<TaskType, number>> = {
  'claude-opus-4-6':           { coding: 97, creative: 95, search: 85, analysis: 98, chat: 92 },
  'claude-sonnet-4-6':         { coding: 92, creative: 90, search: 84, analysis: 93, chat: 90 },
  'claude-haiku-4-5':          { coding: 75, creative: 72, search: 78, analysis: 72, chat: 80 },
  'gpt-4o':                    { coding: 93, creative: 92, search: 88, analysis: 94, chat: 93 },
  'gpt-4o-mini':               { coding: 78, creative: 75, search: 82, analysis: 76, chat: 82 },
  'o3':                        { coding: 98, creative: 80, search: 82, analysis: 99, chat: 78 },
  'o4-mini':                   { coding: 91, creative: 76, search: 80, analysis: 93, chat: 82 },
  'gemini-2.0-flash':          { coding: 80, creative: 78, search: 92, analysis: 82, chat: 85 },
  'gemini-2.5-pro':            { coding: 91, creative: 88, search: 93, analysis: 95, chat: 88 },
  'llama-3.3-70b-versatile':   { coding: 85, creative: 80, search: 83, analysis: 82, chat: 86 },
  'mixtral-8x7b-32768':        { coding: 74, creative: 72, search: 76, analysis: 72, chat: 78 },
  'openrouter/auto':           { coding: 70, creative: 70, search: 75, analysis: 70, chat: 75 },
  'openrouter/claude-3.5-sonnet': { coding: 92, creative: 90, search: 84, analysis: 93, chat: 90 },
  'openrouter/deepseek-r1':    { coding: 95, creative: 74, search: 78, analysis: 96, chat: 74 },
  'grok-3':                    { coding: 89, creative: 85, search: 87, analysis: 90, chat: 88 },
  'grok-3-mini':               { coding: 80, creative: 76, search: 83, analysis: 80, chat: 83 },
  'mistral-large-2411':        { coding: 86, creative: 84, search: 80, analysis: 87, chat: 85 },
  'mistral-small-2409':        { coding: 72, creative: 70, search: 74, analysis: 72, chat: 75 },
  'codestral-2501':            { coding: 90, creative: 60, search: 65, analysis: 75, chat: 65 },
  'command-r-plus-08-2024':    { coding: 82, creative: 80, search: 88, analysis: 84, chat: 83 },
  'command-r-08-2024':         { coding: 70, creative: 68, search: 82, analysis: 70, chat: 74 },
  'sonar-pro':                 { coding: 75, creative: 70, search: 96, analysis: 82, chat: 78 },
  'sonar':                     { coding: 65, creative: 62, search: 92, analysis: 72, chat: 72 },
  'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo': { coding: 88, creative: 84, search: 82, analysis: 86, chat: 85 },
  'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo':  { coding: 83, creative: 78, search: 80, analysis: 81, chat: 83 },
  'accounts/fireworks/models/llama-v3p1-70b-instruct': { coding: 82, creative: 77, search: 79, analysis: 80, chat: 82 },
  'accounts/fireworks/models/deepseek-r1':          { coding: 94, creative: 73, search: 76, analysis: 95, chat: 73 },
  'meta-llama/Meta-Llama-3.1-8B-Instruct':         { coding: 65, creative: 62, search: 68, analysis: 62, chat: 70 },
  'mistralai/Mistral-7B-Instruct-v0.3':             { coding: 62, creative: 65, search: 68, analysis: 60, chat: 70 },
  'deepseek-chat':             { coding: 90, creative: 80, search: 78, analysis: 88, chat: 82 },
  'deepseek-reasoner':         { coding: 95, creative: 74, search: 76, analysis: 96, chat: 72 },
  'ollama/llama3.2':           { coding: 72, creative: 68, search: 70, analysis: 68, chat: 74 },
  'ollama/qwen2.5-coder':      { coding: 84, creative: 55, search: 60, analysis: 70, chat: 60 },
  'azure/gpt-4o':              { coding: 93, creative: 92, search: 88, analysis: 94, chat: 93 },
  'bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0': { coding: 92, creative: 90, search: 84, analysis: 93, chat: 90 },
  'bedrock/meta.llama3-1-70b-instruct-v1:0':        { coding: 83, creative: 78, search: 80, analysis: 81, chat: 83 },
  'meta/meta-llama-3.1-405b-instruct':              { coding: 88, creative: 84, search: 82, analysis: 86, chat: 85 },
};

// Speed scores (0-100, higher = faster)
export const SPEED_SCORES: Record<string, number> = {
  'claude-opus-4-6': 40,
  'claude-sonnet-4-6': 70,
  'claude-haiku-4-5': 90,
  'gpt-4o': 65,
  'gpt-4o-mini': 92,
  'o3': 30,
  'o4-mini': 65,
  'gemini-2.0-flash': 95,
  'gemini-2.5-pro': 60,
  'llama-3.3-70b-versatile': 95,
  'mixtral-8x7b-32768': 97,
  'openrouter/auto': 80,
  'openrouter/claude-3.5-sonnet': 70,
  'openrouter/deepseek-r1': 45,
  'grok-3': 68,
  'grok-3-mini': 90,
  'mistral-large-2411': 62,
  'mistral-small-2409': 92,
  'codestral-2501': 90,
  'command-r-plus-08-2024': 60,
  'command-r-08-2024': 88,
  'sonar-pro': 65,
  'sonar': 90,
  'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo': 50,
  'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo': 85,
  'accounts/fireworks/models/llama-v3p1-70b-instruct': 90,
  'accounts/fireworks/models/deepseek-r1': 40,
  'meta-llama/Meta-Llama-3.1-8B-Instruct': 78,
  'mistralai/Mistral-7B-Instruct-v0.3': 82,
  'deepseek-chat': 70,
  'deepseek-reasoner': 35,
  'ollama/llama3.2': 65,
  'ollama/qwen2.5-coder': 62,
  'azure/gpt-4o': 63,
  'bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0': 68,
  'bedrock/meta.llama3-1-70b-instruct-v1:0': 82,
  'meta/meta-llama-3.1-405b-instruct': 48,
};
